name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * 1"

permissions:
  packages: write
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
      
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ericc-ch/copilot-api
          ref: master
          path: copilot-api

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract short SHA
        id: sha
        working-directory: ./copilot-api
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./copilot-api
          push: true
          tags: ghcr.io/kreatoo/copilot-api-docker:${{ env.SHORT_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/arm64,linux/amd64

      - name: Create and push tag
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag ${{ env.SHORT_SHA }} || true 
          git push origin ${{ env.SHORT_SHA }} || true
          gh release create ${{ env.SHORT_SHA }} --generate-notes || true
          
